# Site settings
title:          Serious Coding Park
description:    "Serious Coding Park"
#baseurl:        "/home"
url:            "https://jinseriouspark.github.io"


# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Jinserious Park
  url:          https://jinseriouspark.com
  email:        jseulpark@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages
  -Paper-Review

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
